# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def __init__(self, MainWindow,loginWindow):
        self.loginWindow = loginWindow
        self.MainWindow = MainWindow
        self.setupUi(self.MainWindow)
        self.MainWindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 612)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 220, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.register_heroImage = QtWidgets.QLabel(self.centralwidget)
        self.register_heroImage.setGeometry(QtCore.QRect(0, 0, 1061, 600))
        self.register_heroImage.setStyleSheet("background-image: url(:/Assets/assets/CreatePassword.png);")
        self.register_heroImage.setText("")
        self.register_heroImage.setObjectName("register_heroImage")
        self.login_password = QtWidgets.QLineEdit(self.centralwidget)
        self.login_password.setGeometry(QtCore.QRect(410, 340, 241, 31))
        self.login_password.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.login_password.setAlignment(QtCore.Qt.AlignCenter)
        self.login_password.setObjectName("login_password")
        self.createAccountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.createAccountBtn.setGeometry(QtCore.QRect(410, 420, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createAccountBtn.sizePolicy().hasHeightForWidth())
        self.createAccountBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.createAccountBtn.setFont(font)
        self.createAccountBtn.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #536DFE;\n"
"color: white;\n"
"background-color: #536DFE;\n"
"text-align: center;\n"
"padding-bottom: 4px;")
        self.createAccountBtn.setObjectName("createAccountBtn")
        self.login_email = QtWidgets.QLineEdit(self.centralwidget)
        self.login_email.setGeometry(QtCore.QRect(410, 300, 241, 31))
        self.login_email.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.login_email.setAlignment(QtCore.Qt.AlignCenter)
        self.login_email.setObjectName("login_email")
        self.login_confirmPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.login_confirmPassword.setGeometry(QtCore.QRect(410, 380, 241, 31))
        self.login_confirmPassword.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.login_confirmPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.login_confirmPassword.setObjectName("login_confirmPassword")
        self.register_heroImage.raise_()
        self.label_3.raise_()
        self.login_password.raise_()
        self.createAccountBtn.raise_()
        self.login_email.raise_()
        self.login_confirmPassword.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.createAccountBtn.clicked.connect(lambda: self.show_LoginPage())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Register"))
        self.login_password.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.createAccountBtn.setText(_translate("MainWindow", "Create Account"))
        self.login_email.setPlaceholderText(_translate("MainWindow", "Enter NRIC"))
        self.login_confirmPassword.setPlaceholderText(_translate("MainWindow", "Confirm your password again"))

    def show_LoginPage(self):
        self.window = QtWidgets.QMainWindow()
        self.loginWindow.show()
        self.MainWindow.hide()

import background_image
