# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InsuranceDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


import mysql.connector
my_db = mysql.connector.connect(host="116.205.136.149",
                                port="3306",
                                user="root",
                                passwd="marron123!",
                                database="onehealth",
                                autocommit=True)
my_cursor = my_db.cursor()

class Ui_MainWindow(object):
    def __init__(self, MainWindow,homeWindow,insuranceDetails):
        self.homeWindow = homeWindow
        self.insuranceDetails = insuranceDetails
        self.MainWindow = MainWindow
        self.setupUi(self.MainWindow)
        self.load_details(insuranceDetails)
        self.MainWindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 30, 691, 411))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.plainTextEdit.setGeometry(QtCore.QRect(160, 170, 391, 141))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_36 = QtWidgets.QLabel(self.groupBox_11)
        self.label_36.setGeometry(QtCore.QRect(30, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Light")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.search_isbn_5 = QtWidgets.QLineEdit(self.groupBox_11)
        self.search_isbn_5.setGeometry(QtCore.QRect(160, 120, 391, 21))
        self.search_isbn_5.setReadOnly(True)
        self.search_isbn_5.setObjectName("search_isbn_5")
        self.label_40 = QtWidgets.QLabel(self.groupBox_11)
        self.label_40.setGeometry(QtCore.QRect(30, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Light")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_40.setObjectName("label_40")
        self.search_category_3 = QtWidgets.QLineEdit(self.groupBox_11)
        self.search_category_3.setGeometry(QtCore.QRect(160, 80, 391, 21))
        self.search_category_3.setReadOnly(True)
        self.search_category_3.setObjectName("search_category_3")
        self.label_38 = QtWidgets.QLabel(self.groupBox_11)
        self.label_38.setGeometry(QtCore.QRect(30, 70, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Raleway Light")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.search_author_3 = QtWidgets.QLineEdit(self.groupBox_11)
        self.search_author_3.setGeometry(QtCore.QRect(160, 40, 391, 21))
        self.search_author_3.setReadOnly(True)
        self.search_author_3.setObjectName("search_author_3")
        self.label_39 = QtWidgets.QLabel(self.groupBox_11)
        self.label_39.setGeometry(QtCore.QRect(30, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway Light")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 350, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_3.clicked.connect(lambda: self.show_homeWindow())

    def show_homeWindow(self):
        self.homeWindow.show()
        self.MainWindow.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Insurance Details"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p>Description</p></body></html>"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p>Age Range</p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>Company</p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p>Insurance ID</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Back"))

    def load_details(self,details):
        my_cursor.execute("SELECT insuranceId, insuranceCompany, minAge, maxAge, description "
                          "FROM insurance "
                          "WHERE insuranceId = %s",(details,))
        rows = my_cursor.fetchall()
        self.search_author_3.setText(rows[0][0])
        self.search_category_3.setText(rows[0][1])
        self.search_isbn_5.setText(str(rows[0][2]) + " - " + str(rows[0][3]))
        self.plainTextEdit.appendPlainText(rows[0][4])


