# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PatientHome import Ui_MainWindow as patientHome
from DoctorHome import Ui_MainWindow as doctorHome
from CreateAccount import Ui_MainWindow as createAccount
import mysql.connector

my_db = mysql.connector.connect(host="116.205.136.149",
                                port="3306",
                                user="root",
                                passwd="marron123!",
                                database="onehealth",
                                autocommit=True)
my_cursor = my_db.cursor()


class Ui_MainWindow(object):
    def __init__(self, MainWindow):
        self.MainWindow = MainWindow
        self.setupUi(self.MainWindow)
        self.MainWindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 612)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1057, 598))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.signInBtn = QtWidgets.QPushButton(self.centralwidget)
        self.signInBtn.setGeometry(QtCore.QRect(410, 390, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signInBtn.sizePolicy().hasHeightForWidth())
        self.signInBtn.setSizePolicy(sizePolicy)
        self.signInBtn.setMinimumSize(QtCore.QSize(241, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.signInBtn.setFont(font)
        self.signInBtn.setStyleSheet("border-radius: 5px;\n"
                                     "border: 1px solid #536DFE;\n"
                                     "color: white;\n"
                                     "background-color: #536DFE;\n"
                                     "text-align: center;\n"
                                     "padding-bottom: 4px;")
        self.signInBtn.setObjectName("signInBtn")
        self.login_nric = QtWidgets.QLineEdit(self.centralwidget)
        self.login_nric.setGeometry(QtCore.QRect(410, 310, 241, 31))
        self.login_nric.setMinimumSize(QtCore.QSize(241, 31))
        self.login_nric.setStyleSheet("border-radius: 5px;\n"
                                      "border: 1px solid white;")
        self.login_nric.setAlignment(QtCore.Qt.AlignCenter)
        self.login_nric.setObjectName("login_nric")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 230, 231, 71))
        self.label_3.setMinimumSize(QtCore.QSize(231, 71))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.login_heroImage = QtWidgets.QLabel(self.centralwidget)
        self.login_heroImage.setGeometry(QtCore.QRect(0, 0, 2061, 1200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_heroImage.sizePolicy().hasHeightForWidth())
        self.login_heroImage.setSizePolicy(sizePolicy)
        self.login_heroImage.setMinimumSize(QtCore.QSize(2061, 1200))
        self.login_heroImage.setStyleSheet("background-image: url(:/Assets/assets/Login.png);")
        self.login_heroImage.setText("")
        self.login_heroImage.setObjectName("login_heroImage")
        self.login_password = QtWidgets.QLineEdit(self.centralwidget)
        self.login_password.setGeometry(QtCore.QRect(410, 350, 241, 31))
        self.login_password.setMinimumSize(QtCore.QSize(241, 31))
        self.login_password.setStyleSheet("border-radius: 5px;\n"
                                          "border: 1px solid white;")
        self.login_password.setAlignment(QtCore.Qt.AlignCenter)
        self.login_password.setObjectName("login_password")
        self.registerAccountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.registerAccountBtn.setGeometry(QtCore.QRect(460, 430, 151, 31))
        self.registerAccountBtn.setMinimumSize(QtCore.QSize(151, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.registerAccountBtn.setFont(font)
        self.registerAccountBtn.setStyleSheet("background-color: transparent;\n"
                                              "")
        self.registerAccountBtn.setObjectName("registerAccountBtn")
        self.forgetPasswordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.forgetPasswordBtn.setGeometry(QtCore.QRect(460, 460, 151, 31))
        self.forgetPasswordBtn.setMinimumSize(QtCore.QSize(151, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.forgetPasswordBtn.setFont(font)
        self.forgetPasswordBtn.setStyleSheet("background-color: transparent;\n"
                                             "")
        self.forgetPasswordBtn.setObjectName("forgetPasswordBtn")
        self.login_heroImage.raise_()
        self.signInBtn.raise_()
        self.login_nric.raise_()
        self.label_3.raise_()
        self.login_password.raise_()
        self.registerAccountBtn.raise_()
        self.forgetPasswordBtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Button assignment
        # Login button
        self.signInBtn.clicked.connect(lambda: self.show_window())
        self.registerAccountBtn.clicked.connect(lambda: self.show_createAccount())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signInBtn.setText(_translate("MainWindow", "Sign in"))
        self.login_nric.setPlaceholderText(_translate("MainWindow", "Enter NRIC"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Log In</p></body></html>"))
        self.login_password.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.registerAccountBtn.setText(_translate("MainWindow", "Register Account"))
        self.forgetPasswordBtn.setText(_translate("MainWindow", "Forget Password"))

    # For create account
    def show_createAccount(self):
        self.window = QtWidgets.QMainWindow()
        createAccount(self.window, self.MainWindow)
        MainWindow.hide()

    # For Login
    # Check credentials
    def check_credentials(self):
        user = self.login_nric.text()
        my_cursor.execute("SELECT EXISTS(SELECT * FROM patient WHERE patientId = %s)", (user,))
        rows = my_cursor.fetchall()
        if str(rows[0][0]) == "1":
            return True
        else:
            return False

    # Check doctor credentials
    def check_doctor_credentials(self):
        user = self.login_nric.text()
        password = self.login_password.text()
        my_cursor.execute("SELECT EXISTS(SELECT * FROM doctor WHERE doctorId = %s)", (user,))
        rows = my_cursor.fetchall()
        if str(rows[0][0]) == "1":
            return True
        else:
            return False

    # Open Patient Home
    def show_patient_window(self):
        self.window = QtWidgets.QMainWindow()
        details = str(self.login_nric.text())
        patientHome(details, self.window, self.MainWindow)
        MainWindow.hide()

    # Open Doctor Home
    def show_doctor_window(self):
        self.window = QtWidgets.QMainWindow()
        details = str(self.login_nric.text())
        doctorHome(self.window, self.MainWindow, details)
        MainWindow.hide()

    # Show required window
    def show_window(self):
        if self.check_credentials():
            self.show_patient_window()
        elif self.check_doctor_credentials():
            self.show_doctor_window()
        else:
            self.error_popup()

    # Error Popup
    def error_popup(self):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("wrong credentials")
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.exec_()


import background_image

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
