# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConsultationInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
my_db = mysql.connector.connect(host="116.205.136.149",
                                port="3306",
                                user="root",
                                passwd="marron123!",
                                database="onehealth",
                                autocommit=True)
my_cursor = my_db.cursor()

class Ui_MainWindow(object):
    def __init__(self, MainWindow,doctorWindow,docDetails):
        self.doctorWindow = doctorWindow
        self.MainWindow = MainWindow
        self.setupUi(self.MainWindow)
        self.docDetails = docDetails
        self.MainWindow.show()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(30, 20, 881, 591))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_41 = QtWidgets.QLabel(self.groupBox_11)
        self.label_41.setGeometry(QtCore.QRect(480, 120, 121, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_40 = QtWidgets.QLabel(self.groupBox_11)
        self.label_40.setGeometry(QtCore.QRect(480, 240, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.search_yeadateInputer_3 = QtWidgets.QLineEdit(self.groupBox_11)
        self.search_yeadateInputer_3.setGeometry(QtCore.QRect(160, 120, 241, 21))
        self.search_yeadateInputer_3.setObjectName("search_yeadateInputer_3")
        self.label_37 = QtWidgets.QLabel(self.groupBox_11)
        self.label_37.setGeometry(QtCore.QRect(20, 120, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Raleway Light")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_36 = QtWidgets.QLabel(self.groupBox_11)
        self.label_36.setGeometry(QtCore.QRect(20, 160, 131, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.idInout = QtWidgets.QLineEdit(self.groupBox_11)
        self.idInout.setGeometry(QtCore.QRect(160, 80, 241, 21))
        self.idInout.setObjectName("idInout")
        self.label_38 = QtWidgets.QLabel(self.groupBox_11)
        self.label_38.setGeometry(QtCore.QRect(20, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Raleway Light")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.nameInput = QtWidgets.QLineEdit(self.groupBox_11)
        self.nameInput.setGeometry(QtCore.QRect(160, 40, 241, 21))
        self.nameInput.setObjectName("nameInput")
        self.label_39 = QtWidgets.QLabel(self.groupBox_11)
        self.label_39.setGeometry(QtCore.QRect(20, 40, 121, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.saveBtn = QtWidgets.QPushButton(self.groupBox_11)
        self.saveBtn.setGeometry(QtCore.QRect(30, 430, 75, 23))
        self.saveBtn.setObjectName("saveBtn")
        self.backBtn = QtWidgets.QPushButton(self.groupBox_11)
        self.backBtn.setGeometry(QtCore.QRect(150, 430, 75, 23))
        self.backBtn.setObjectName("backBtn")
        self.diagnosisInput = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.diagnosisInput.setGeometry(QtCore.QRect(160, 160, 241, 81))
        self.diagnosisInput.setObjectName("diagnosisInput")
        self.remarkInput = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.remarkInput.setGeometry(QtCore.QRect(620, 240, 241, 81))
        self.remarkInput.setObjectName("remarkInput")
        self.followUpInput = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.followUpInput.setGeometry(QtCore.QRect(620, 120, 241, 81))
        self.followUpInput.setObjectName("followUpInput")
        self.facilityNameInput = QtWidgets.QLineEdit(self.groupBox_11)
        self.facilityNameInput.setGeometry(QtCore.QRect(620, 40, 241, 21))
        self.facilityNameInput.setReadOnly(True)
        self.facilityNameInput.setObjectName("facilityNameInput")
        self.label_42 = QtWidgets.QLabel(self.groupBox_11)
        self.label_42.setGeometry(QtCore.QRect(480, 40, 121, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_11)
        self.label_43.setGeometry(QtCore.QRect(480, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.doctorNameInput = QtWidgets.QLineEdit(self.groupBox_11)
        self.doctorNameInput.setGeometry(QtCore.QRect(620, 80, 241, 21))
        self.doctorNameInput.setReadOnly(True)
        self.doctorNameInput.setObjectName("doctorNameInput")
        self.label_44 = QtWidgets.QLabel(self.groupBox_11)
        self.label_44.setGeometry(QtCore.QRect(20, 270, 121, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.servicesInput = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.servicesInput.setGeometry(QtCore.QRect(160, 270, 241, 81))
        self.servicesInput.setObjectName("servicesInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #back button
        self.backBtn.clicked.connect(lambda: self.show_DoctorHome())

        #save button
        self.saveBtn.clicked.connect(lambda: self.save_returnBack())

    def save_returnBack(self):
        #add insert to sql code here!!!
        self.doctorWindow.show()
        self.MainWindow.close()
    
    def show_DoctorHome(self):
        self.doctorWindow.show()
        self.MainWindow.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Consultation Details"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>Follow-up Action</p></body></html>"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p>Remarks</p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p>Date</p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p>Diagnosis</p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>Patient ID</p><p><br/></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p>Patient Name</p></body></html>"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.backBtn.setText(_translate("MainWindow", "Back"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p>Facility Name</p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p>Doctor Name</p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p>Services</p></body></html>"))






